model:
  name: klue/roberta-small

training:
  epochs: 1
  batch_size: 16
  learning_rate: 0.00001
  optimizer: Adam
  loss: L1loss
  shuffle: True

data:
  max_tokens: 160
  augmentation:
    method: swap_sentences
    probability: 0.1

path:
  train: data/train.csv
  dev: data/dev.csv
  test: data/dev.csv
  predict: data/test.csv # not predict.csv