model:
  name: snunlp/KR-ELECTRA-discriminator

seed: 42

training:
  epochs: 3
  batch_size: 32
  learning_rate: 0.00001
  optimizer: AdamW
  loss: L1loss
  shuffle: True
  weight_decay: 0.01
  scheduler: CosineAnnealingLR

data:
  dropout_rate: 0.1
  max_tokens: 160
  augmentation:
    - method: swap_sentences
      params:
        probability: 1.0
  under_sampling:
    - method: undersample_label_0
      params:
        probability: 0.5

path:
  train: data/train.csv
  dev: data/dev.csv
  test: data/dev.csv
  predict: data/test.csv
